Improve arity error message
The `arity` package's error messages are currently pretty bad; a failure
from passing too many args results in an error like:

```
error: bad arity: got 2
```

And that's just not helpful to anyone. This change modifies the package
to provide useful and helpful diagnostics to the user so that it's
explicit:

```
error: accepts at most 1 argument, but received 2
```

Change-Category: feature
Change-Impact: additive
Component: flag